log_options = ('---',
    'P00. PROJECT INITIAL REVIEW',
    'P01. INTERNAL KICK OFF',
    'P02. EXTERNAL KICK OFF',
    'P03. CONFIG TEMPLATES',
    'P04. INSTALLATION (ONGOING)',
    'P05. DOCUMENTATION (ONGOING)',
    'P06. INTERNAL FOLLOW-UP MEETING',
    'P07. EXTERNAL FOLLOW-UP MEETING',
    'P08. CSC TASK CREATION',
    'N01. SPECIALIST ASSIGNED',
    'N02. TEMPLATES SENT',
    'N03. ACTIVITIES COMPLETED',
    'N04. HANDOVER ACCEPTED BY CSC',
    'N05. PROJECT HALTED',
    'N06. WO CANCELLED',
    'N07. PENDING INTERNAL KICK OFF',
    'N08. PENDING EXTERNAL KICK OFF',
    'N09. PENDING RESOURCES',
    'N10. RESOURCES CHANGES',
    'N11. INSTALLATION DELAYED',
    'N12. INSTALLATION COMPLETED',
    'N13. MONITORING',
    'N14. ADDED TO FORTICLOUD',
    'N15. ADDED TO RADIUS/RANCID',
    'N16. THIRD-PARTY ESCALATION',
    'N17. RETURNED DUE TO INACTIVITY',
    'N18. PARTIAL HANDOVER',
    'N19. SLA CROSSED',
    'N20. MAINTENANCE WINDOW STARTED',
    'N21. MAINTENANCE WINDOW COMPLETED',
    'N22. HANDOVER ADJUSTMENTS',
    'N23. CHANGE CONTROL FORMAT SENT',
    'N24. LICENSES ADDED',
    'N25. CUSTOMER TRAINING',
    'N26. TROUBLESHOOTING/FIXES/ADJUSTMENTS',
    'N27. NOTE',

    )

log_options_spanish = ('---',
    'P00. REVISION PRELIMINAR DEL PROYECTO',
    'P01. KO INTERNO (KOI)',
    'P02. KO EXTERNO (KOE)',
    'P03. PLANTILLA ALISTAMIENTO',
    'P04. PEM (EJECUCION)',
    'P05. DOCUMENTACION (PREPARACION)',
    'P06. REUNION SEGUIMIENTO - INTERNA',
    'P07. REUNION SEGUIMIENTO - CLIENTE',
    'P08. CSC (CREACION TAREA)',
    'N01. ESPECIALISTA ASIGNADO',
    'N02. PLANTILLA ENVIADA',
    'N03. ACTIVIDADES FINALIZADAS',
    'N04. CSC (ENTREGA ACEPTADA)',
    'N05. WO SIN ACTIVIDAD',
    'N06. WO CANCELADA',
    'N07. KOI PENDIENTE',
    'N08. KOE PENDIENTE',
    'N09. RECURSOS PENDIENTES',
    'N10. RECURSOS CAMBIADOS',
    'N11. PEM DEMORADA',
    'N12. PEM COMPLETA',
    'N13. EN MONITOREO',
    'N14. FORTICLOUD AGREGADO',
    'N15. RADIUS AGREGADO',
    'N16. ESCALAMIENTO A TERCERO',
    'N17. DEVOLUCION PM x INACTIVIDAD',
    'N18. ENTREGA PARCIAL',
    'N19. CIERRE WO POR SLA',
    'N20. INICIO DE VENTANA MTO',
    'N21. FINAL DE VENTANA MTO',
    'N22. AJUSTES EN LA ENTREGA',
    'N23. FORMATO DE CONTROL DE CAMBIOS ENVIADO',
    'N24. SE AÑADEN LICENCIAS',
    'N25. CAPACITACION AL CLIENTE',
    'N26. SOLUCION DE PROBLEMAS/REPARACIONES/AJUSTES',
    'N27. NOTA/COMENTARIO'
    )

default_mw_text_1="""rfc: <RFC>
status: STARTED
start_date: yyyy-mm-dd hh:mm
end_date: yyyy-mm-dd hh:mm
details: <MW INFO>
"""
default_mw_text_2="""rfc: <RFC>
status: COMPLETED
start_date: yyyy-mm-dd hh:mm
end_date: yyyy-mm-dd hh:mm
details: <MW INFO>
"""